<a href="https://colab.research.google.com/github/itsmepriyabrata/priyabrata_ai_python/blob/main/DAY3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array = np.array([[1, 2],
                  [3, 4],
                  [5, 6],
                  [7, 8]])

print("Array:")
print(array)

print("\nShape of array:", array.shape)

print("Number of dimensions:", array.ndim)

print("Data type of array elements:", array.dtype)

print("Number of elements in the array:", array.size)

print("Size of each element in bytes:", array.itemsize, "bytes")

print("Total size of the array in bytes:", array.nbytes, "bytes")


Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Shape of array: (4, 2)
Number of dimensions: 2
Data type of array elements: int64
Number of elements in the array: 8
Size of each element in bytes: 8 bytes
Total size of the array in bytes: 64 bytes


In [2]:
import numpy as np

arr_range = np.arange(100, 200, 10)

array = arr_range.reshape(5, 2)

# Print the resulting array
print("5x2 Array:")
print(array)


5x2 Array:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [3]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

third_column = array[:, 2]

# Printing the array of items from the third column
print("Array of items from the third column:")
print(third_column)


Array of items from the third column:
[3 6 9]


In [4]:
import numpy as np

# Given NumPy array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16],
                  [17, 18, 19, 20]])

odd_rows_even_columns = array[::2, 1::2]

# Printing the resulting array
print("Array of odd rows and even columns:")
print(odd_rows_even_columns)


Array of odd rows and even columns:
[[ 2  4]
 [10 12]
 [18 20]]


In [5]:
import numpy as np

# Two NumPy arrays
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

result_array = array1 + array2

result_array_squared = result_array ** 2

# Printing the result array and the modified result array
print("Result array after addition:")
print(result_array)

print("\nResult array after squaring each element:")
print(result_array_squared)


Result array after addition:
[[ 6  8]
 [10 12]]

Result array after squaring each element:
[[ 36  64]
 [100 144]]
