<a href="https://colab.research.google.com/github/itsmepriyabrata/priyabrata_ai_python/blob/main/GRU_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
pip install tensorflow


In [15]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.GRU(64, input_shape=(28, 28)))
model.add(layers.BatchNormalization())
model.add(layers.Dense(10))
print(model.summary())
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0
x_validate, y_validate = x_test[:-10], y_test[:-10]
x_test, y_test = x_test[-10:], y_test[-10:]
print(x_test,y_test)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_3 (GRU)                 (None, 64)                18048     
                                                                 
 batch_normalization_3 (Bat  (None, 64)                256       
 chNormalization)                                                
                                                                 
 dense_3 (Dense)             (None, 10)                650       
                                                                 
Total params: 18954 (74.04 KB)
Trainable params: 18826 (73.54 KB)
Non-trainable params: 128 (512.00 Byte)
_________________________________________________________________
None
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0

In [16]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer="sgd",
    metrics=["accuracy"],
)

In [6]:
model.fit(
    x_train, y_train, validation_data=(x_validate, y_validate), batch_size=64, epochs=10
)

Epoch 1/10
938/938 [==============================] - 17s 16ms/step - loss: 1.4094 - accuracy: 0.5264 - val_loss: 1.0062 - val_accuracy: 0.6755
Epoch 2/10
938/938 [==============================] - 16s 17ms/step - loss: 0.7634 - accuracy: 0.7533 - val_loss: 0.5724 - val_accuracy: 0.8078
Epoch 3/10
938/938 [==============================] - 16s 17ms/step - loss: 0.4841 - accuracy: 0.8490 - val_loss: 0.6310 - val_accuracy: 0.7805
Epoch 4/10
938/938 [==============================] - 15s 16ms/step - loss: 0.3587 - accuracy: 0.8915 - val_loss: 0.3017 - val_accuracy: 0.9067
Epoch 5/10
938/938 [==============================] - 15s 16ms/step - loss: 0.2772 - accuracy: 0.9166 - val_loss: 0.2262 - val_accuracy: 0.9312
Epoch 6/10
938/938 [==============================] - 15s 16ms/step - loss: 0.2224 - accuracy: 0.9335 - val_loss: 0.1841 - val_accuracy: 0.9404
Epoch 7/10
938/938 [==============================] - 16s 17ms/step - loss: 0.1892 - accuracy: 0.9427 - val_loss: 0.3022 - val_accuracy:

In [18]:
for i in range(10):
    result = tf.argmax(model.predict(tf.expand_dims(x_test[i], 0)), axis=1)
    print(result.numpy(), y_test[i])

1/1 [==============================] - 0s 403ms/step
[8] 7
1/1 [==============================] - 0s 19ms/step
[8] 8
1/1 [==============================] - 0s 19ms/step
[8] 9
1/1 [==============================] - 0s 23ms/step
[8] 0
1/1 [==============================] - 0s 27ms/step
[8] 1
1/1 [==============================] - 0s 23ms/step
[8] 2
1/1 [==============================] - 0s 22ms/step
[8] 3
1/1 [==============================] - 0s 23ms/step
[8] 4
1/1 [==============================] - 0s 22ms/step
[8] 5
1/1 [==============================] - 0s 19ms/step
[8] 6
