<a href="https://colab.research.google.com/github/itsmepriyabrata/priyabrata_ai_python/blob/main/GRU_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.GRU(64, input_shape=(28, 28)))
model.add(layers.BatchNormalization())
model.add(layers.Dense(10))
print(model.summary())
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0
x_validate, y_validate = x_test[:-10], y_test[:-10]
x_test, y_test = x_test[-10:], y_test[-10:]
print(x_test,y_test)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_3 (GRU)                 (None, 64)                18048     
                                                                 
 batch_normalization_3 (Bat  (None, 64)                256       
 chNormalization)                                                
                                                                 
 dense_3 (Dense)             (None, 10)                650       
                                                                 
Total params: 18954 (74.04 KB)
Trainable params: 18826 (73.54 KB)
Non-trainable params: 128 (512.00 Byte)
_________________________________________________________________
None
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0

In [ ]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer="sgd",
    metrics=["accuracy"],
)

In [ ]:
model.fit(
    x_train, y_train, validation_data=(x_validate, y_validate), batch_size=64, epochs=10
)

Epoch 1/10
938/938 [==============================] - 17s 16ms/step - loss: 1.4094 - accuracy: 0.5264 - val_loss: 1.0062 - val_accuracy: 0.6755
Epoch 2/10
938/938 [==============================] - 16s 17ms/step - loss: 0.7634 - accuracy: 0.7533 - val_loss: 0.5724 - val_accuracy: 0.8078
Epoch 3/10
938/938 [==============================] - 16s 17ms/step - loss: 0.4841 - accuracy: 0.8490 - val_loss: 0.6310 - val_accuracy: 0.7805
Epoch 4/10
938/938 [==============================] - 15s 16ms/step - loss: 0.3587 - accuracy: 0.8915 - val_loss: 0.3017 - val_accuracy: 0.9067
Epoch 5/10
938/938 [==============================] - 15s 16ms/step - loss: 0.2772 - accuracy: 0.9166 - val_loss: 0.2262 - val_accuracy: 0.9312
Epoch 6/10
938/938 [==============================] - 15s 16ms/step - loss: 0.2224 - accuracy: 0.9335 - val_loss: 0.1841 - val_accuracy: 0.9404
Epoch 7/10
938/938 [==============================] - 16s 17ms/step - loss: 0.1892 - accuracy: 0.9427 - val_loss: 0.3022 - val_accuracy:

In [ ]:
for i in range(10):
    result = tf.argmax(model.predict(tf.expand_dims(x_test[i], 0)), axis=1)
    print(result.numpy(), y_test[i])

1/1 [==============================] - 0s 403ms/step
[8] 7
1/1 [==============================] - 0s 19ms/step
[8] 8
1/1 [==============================] - 0s 19ms/step
[8] 9
1/1 [==============================] - 0s 23ms/step
[8] 0
1/1 [==============================] - 0s 27ms/step
[8] 1
1/1 [==============================] - 0s 23ms/step
[8] 2
1/1 [==============================] - 0s 22ms/step
[8] 3
1/1 [==============================] - 0s 23ms/step
[8] 4
1/1 [==============================] - 0s 22ms/step
[8] 5
1/1 [==============================] - 0s 19ms/step
[8] 6


In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.GRU(64, input_shape=(28, 28)))
model.add(layers.BatchNormalization())
model.add(layers.Dense(10))

print(model.summary())

mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_validate, y_validate = x_test[:-10], y_test[:-10]
x_test, y_test = x_test[-10:], y_test[-10:]

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer="sgd",
    metrics=["accuracy"],
)

model.fit(
    x_train, y_train, validation_data=(x_validate, y_validate), batch_size=64, epochs=10
)

model.save("trained_gru_model.h5")

for i in range(10):
    result = tf.argmax(model.predict(tf.expand_dims(x_test[i], 0)), axis=1)
    print(result.numpy(), y_test[i])


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, 64)                18048     
                                                                 
 batch_normalization (Batch  (None, 64)                256       
 Normalization)                                                  
                                                                 
 dense (Dense)               (None, 10)                650       
                                                                 
Total params: 18954 (74.04 KB)
Trainable params: 18826 (73.54 KB)
Non-trainable params: 128 (512.00 Byte)
_________________________________________________________________
None
11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/10
938/938 [==============================] - 30s 25ms/step - loss: 1.4217 - accuracy: 0.5189 - val_loss: 1.0014 - val_accuracy: 0.6671


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


1/1 [==============================] - 0s 459ms/step
[7] 7
1/1 [==============================] - 0s 23ms/step
[8] 8
1/1 [==============================] - 0s 21ms/step
[4] 9
1/1 [==============================] - 0s 21ms/step
[0] 0
1/1 [==============================] - 0s 23ms/step
[1] 1
1/1 [==============================] - 0s 20ms/step
[2] 2
1/1 [==============================] - 0s 21ms/step
[3] 3
1/1 [==============================] - 0s 21ms/step
[4] 4
1/1 [==============================] - 0s 22ms/step
[5] 5
1/1 [==============================] - 0s 23ms/step
[6] 6


In [17]:
from tensorflow.keras.models import load_model

model = load_model('/content/trained_gru_model.h5')


In [16]:
import numpy as np

def prepare_input(audio_file):
    """
    Prepare input data for the GRU model.

    Parameters:
        audio_file (str): Path to the preprocessed audio data file (in .npy format).

    Returns:
        np.ndarray: Preprocessed input data.
    """
    preprocessed_audio = np.load(audio_file)

    input_data = np.expand_dims(preprocessed_audio, axis=0)  # Add batch dimension

    return input_data
input_data = prepare_input('/content/preprocessed_audio 2.npy')


In [15]:
def predict_class(input_data):
    """
    Perform model inference and predict class label.

    Parameters:
        input_data (np.ndarray): Preprocessed input data.

    Returns:
        np.ndarray: Model prediction.
    """
    prediction = model.predict(input_data)

    return prediction


In [14]:
def interpret_prediction(prediction):
    """
    Interpret the model prediction.

    Parameters:
        prediction (np.ndarray): Model prediction.
    """
    print("Predicted class:", prediction)


In [13]:
import numpy as np
import librosa

def extract_mfcc(audio_file):
    pass

def validate_audio(audio_file):
    pass

validate_audio('/content/drive/MyDrive/AUDIO FOLDER/output_3.wav')
