<a href="https://colab.research.google.com/github/itsmepriyabrata/priyabrata_ai_python/blob/main/Math1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The code provided calculates various minimum values within a matrix (M) using both NumPy and PyTorch.

In [7]:
# import libraries
import numpy as np
import torch
# create a vector
v = np.array([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')
# repeat with matrix
M = np.array([ [0,1,10], [20,8,5] ])
print(M), print(' ')

# various minima in this matrix!
minvals1 = np.min(M)        # minimum from ENTIRE matrix
minvals2 = np.min(M,axis=0) # minimum of each column (across rows)
minvals3 = np.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(minvals1)
print(minvals2)
print(minvals3)
# various minima in this matrix!
minidx1 = np.argmin(M)        # minimum from ENTIRE matrix
minidx2 = np.argmin(M,axis=0) # minimum of each column (across rows)
minidx3 = np.argmin(M,axis=1) # minimum of each row (across columns)

# print them out
print(M), print(' ') # reminder
print(minidx1)
print(minidx2)
print(minidx3)
# create a vector
v = torch.tensor([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# finding the indices of the minimum and maximum values in the array v using NumPy's np.argmin() and np.argmax() functions respectively, and then printing them.
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirming the minimum and maximum values in the array v by printing them using their respective indices.
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')
#  creating a 2D NumPy array M containing two rows and three columns and then printing it.
M = torch.tensor([ [0,1,10], [20,8,5] ])
print(M), print(' ')

# various minima in this matrix!
min1 = torch.min(M)        # minimum from ENTIRE matrix
min2 = torch.min(M,axis=0) # minimum of each column (across rows)
min3 = torch.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(min1), print(' ')
print(min2), print(' ')
print(min2.values)
print(min2.indices)
min2.count



Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40
[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]
[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]
Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40
tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
tensor([0, 0, 1])


<function min.count(value, /)>